name: Deploy to Staging

on:
  push:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: echo Building application for Staging environment!
    
  DeployStaging:
    permissions: write-all    
    name: Staging
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Staging
      url: 'https://agility-stg.b-yond.com/'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        run: echo Deploying to Staging environment! 
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-html
          
      - name: Run tests
        run: |
          pytest -vv --junit-xml=junit-report.xml
          
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: (!cancelled())
        with:
          files: |
            junit-report.xml
